pipeline:
  build:
    image: node:7
    commands:
      - npm run install
      - npm run generate
  publish:
    gh_pages:
      source: dist
      remote: origin
      branch: master
    when:
      status: success
      branch: dev
