pipeline:
  build:
    image: node:latest
    secrets: [ GH_TOKEN ]
    environment:
      - GH_TOKEN=${GH_TOKEN}
    commands:
      - npm install
      - npm run generate
      - ./deploy
    when:
      branch: dev
