pipeline:
  build:
    image: node:latest
    secrets: [ GH_TOKEN ]
    environment:
      - GH_TOKEN=${GH_TOKEN}
      - BASE_URL=http://ideabile.com/
    commands:
      - npm install
      - node ./index.js generate
      - ./deploy
    when:
      branch: dev
