pipeline:
  build:
    image: node:latest
    environment:
      - GH_TOKEN=${GH_TOKEN}
    commands:
      - npm install
      - ./gh-publish ${GH_TKEN}

publish:
  gh_pages:
    source: dist
    remote: origin
    branch: master
